Suporte ao PHP 8.x
piggly-dev/php-pix pull request #3
Opened 2021-05-09 21:55 UTC by leoneparise

Esta PR adiciona suporte ao PHP 8.x bem como atualiza algumas bibliotecas e corrige alguns testes.

2021-05-13 20:25 UTC, caiquearaujo commented
Vou analisar esse final de semana e, se tiver tudo certo, faço o merge!

2021-05-13 21:14 UTC, caiquearaujo commented
@leoneparise só precisamos corrigir uma coisa, não dá para usar a `chillerlan/php-qrcode` na versão `^4.2`, pois ela retira o suporte ao PHP `7.2`, que deve ser mantido nesta biblioteca. Ou então mudar a linha `"php": "^7.2|^8.0"` para `"php": "^7.4|^8.0"`

2021-05-14 21:45 UTC, caiquearaujo requested changes

2021-05-14 21:45 UTC, caiquearaujo commented on composer.json
> -        "chillerlan/php-qrcode": "^3.3"
Manter a versão `3.3` uma vez que ela suporta o PHP `7.2` que é utilizado pela maioria que adota a biblioteca do Pix.

2021-05-14 21:45 UTC, caiquearaujo commented on composer.json
> +        "phpunit/phpunit": "^9.5"
Migrar para a versão `8.5` no máximo, já que ela permite conduzir os testes na versão `7.2` do PHP.

2021-05-14 21:45 UTC, caiquearaujo commented on composer.json
> +        "phpunit/phpunit": "^9.5"
Não esqueça também de rodar os testes com a versão do PHP `7.2` em diante, inclusive a `8`, para certificar que está tudo certo.

2021-05-17 02:49 UTC, leoneparise commented
Ola @caiquearaujo, fiz alguma correções como adotar a versão mínima do PHP para `7.4` e o downgrade do phpunit para `8.5`. No entanto, devido a biblioteca `chillerlan/php-qrcode` não é possível dar suporte ao PHP `7.2` e `8.x` ao mesmo tempo. A versão `3.x` da biblioteca suporta o PHP `7.2` e a `4.x` o PHP `7.4` em diante. Caso queria fazer merge, sinta-se a vontate, estou usando a versão que se encontra na minha branch em produção sem nenhum problema.

Muito obrigado pela biblioteca, fez um ótimo trabalho. :)

2021-05-17 03:27 UTC, caiquearaujo commented
Entendo, como mudar a versão da biblioteca `chillerlan/php-qrcode` cria incompatibilidades com o PHP `7.2`, vamos precisar avaliar se é mesmo o melhor momento para essa `feature`. Pois, seguindo o **[SimVer](https://semver.org/lang/pt-BR/)** vamos precisar migrar para a versão `2.0` nessa biblioteca.

2021-05-17 16:39 UTC, leoneparise commented
> Entendo, como mudar a versão da biblioteca `chillerlan/php-qrcode` cria incompatibilidades com o PHP `7.2`, vamos precisar avaliar se é mesmo o melhor momento para essa `feature`. Pois, seguindo o **[SimVer](https://semver.org/lang/pt-BR/)** vamos precisar migrar para a versão `2.0` nessa biblioteca.

Exatamente, muitas bibliotecas estão fazendo isso para dar suporte ao PHP 8.

2021-05-26 01:51 UTC, closed without merging

2021-05-26 01:52 UTC, caiquearaujo commented
Vou fechar essa **pull request** para mudar a estrutura dos branches antes de atualizar para a versão 2.x.x da biblioteca.